### ISSUE TITLE
Resalvas:

### ISSUE THREAD

**Issue by makepag** [MicrosoftDocs/xamarin-docs.pt-br#10]
Sendo uma versão 'Hello', acredito que poderia deixar claro que ao instalar o Xamarin, o template vem com o CoordinatorLayout, que não é simplesmente arrastar e soltar os widgets como mostrou no artigo.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: início rápido - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #739](https://github.com/MicrosoftDocs/xamarin-docs/issues/739) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @makepag 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/xamarin-docs/issues/739. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
