### ISSUE TITLE
Socorro!

### ISSUE THREAD

**Issue by Monster1557** [MicrosoftDocs/xamarin-docs.pt-br#18]
Por que quando coloco as caixas de widgets, elas ficam uma em cima da outra?
segue anexo: http://prntscr.com/lkgezh

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 433a2ad1-1ba6-7860-2012-7fe24e79f254
* Version Independent ID: 5c817523-a465-9818-7411-af390402afce
* Content: [Noções básicas sobre níveis de API do Android - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/app-fundamentals/android-api-levels?tabs=windows#related-links)
* Content Source: [docs/android/app-fundamentals/android-api-levels.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/app-fundamentals/android-api-levels.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Olá, @Monster1557,  

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
