### ISSUE TITLE
Não é nenhum problema :^)

### ISSUE THREAD

**Issue by rafaxzx** [MicrosoftDocs/xamarin-docs.pt-br#19]
O meu comentário é pra dizer que segui os passos e funcionou certinho, ok que é BEM trabalhoso sim, e tem uma parte que poderia detalhar melhor sobre achar o app manifest pra garantir que as informações irão bater, mas pra quem está iniciando no mundo de desenvolvimento e está começando no mobile como eu, foi muito gratificante ver meu App exercício com o Xamarin Form rodando no iOS. Obrigado!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 1a9b2b39-f572-75dc-f022-cada4919f129
* Version Independent ID: 804f0f6d-ed12-18d8-30b8-95b5aaa19d8a
* Content: [Provisionamento gratuito para aplicativos Xamarin.iOS - Xamarin](https://docs.microsoft.com/pt-br/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=windows)
* Content Source: [docs/ios/get-started/installation/device-provisioning/free-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/ios/get-started/installation/device-provisioning/free-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by CeciAc** [comment]
Olá, @rafaxzx 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
