### ISSUE TITLE
Vìdeo Player Binding

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [MicrosoftDocs/xamarin-docs.pt-br#20]
Olá, Caros.

Preciso que o player de funcione com ligações (binding).
Assim funciona: 

```
<video:VideoPlayer Source="https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4"
                   AreTransportControlsEnabled="False" />
```

Assim não funciona:

```
<video:VideoPlayer Source="{Binding VideoLink}"
                   AreTransportControlsEnabled="False" />
```

Preciso que funcione assim, pois eu quero usar links dinamicos que são consumidos de uma API, alguma dica ou direção do que devo fazer? 

Referencia:
https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/repo_sync_working_branch/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md

**Comment by andersonvieiragomeslopes** [comment]
O meu problema não possui relação com a documentação? Se não, por qual motivo? responda de forma objetiva, fazendo isso, posso reformular a dúvida se ela foi interpretada de maneira incorreta. @CeciAc

**Comment by CeciAc** [comment]
Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior **da página de DOCS:** https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos

**Comment by andersonvieiragomeslopes** [comment]
@CeciAc , obrigado, eu não sabia como fazer, acabo de abrir o problema seguindo essa orientação.
