### ISSUE TITLE
Alterar icones

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [MicrosoftDocs/xamarin-docs.pt-br#21]
Boa tarde, Caros.

O que devo fazer para alterar os icones do player de vídeo? 
Icones: http://prntscr.com/mdblfv

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 08231611-5a52-267d-cfc6-0042e5d5c2a3
* Version Independent ID: 6c39962d-a013-a391-9f1f-4a69f3a99de0
* Content: [Reproduzindo um vídeo da Web - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LisandroSu** [comment]
Olá, @andersonvieiragomeslopes 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by andersonvieiragomeslopes** [comment]
@LisandroSu a minha dúvida, faz parte diretamente da documentação, pois a alteração é feita no custom renderer.

**Comment by andersonvieiragomeslopes** [comment]
@LisandroSu @chad @AArnott @bgianfo 

> @LisandroSu a minha dúvida, faz parte diretamente da documentação, pois a alteração é feita no custom renderer.
