### ISSUE TITLE
A key store nao aparece na Android Signing identity

### ISSUE THREAD

**Issue by AndersonCrook** [MicrosoftDocs/xamarin-docs.pt-br#23]
Quando vou Criar um Novo Certificado e clico em ok a chave não aparece na aba Android Signing identity, e quando clico em importa keystore o visual studio fecha sosinho

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Assinatura do Pacote de Aplicativos Android - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/deploy-test/signing/index?tabs=macos#feedback)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Olá, @AndersonCrook 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by fercmparedes** [comment]
Olá @AndersonCrook , estou com o mesmo problema. Voce conseguiu resolvê-lo?

**Comment by AndersonCrook** [comment]
> Olá @AndersonCrook , estou com o mesmo problema. Voce conseguiu resolvê-lo?

teve uma atualização esta semana eu atualizei o problema parece ter sido corrigido.

**Comment by fercmparedes** [comment]
Ah blz. Eu tinha conseguido fazer manualmente via terminal, mas ele
arrumaram o erro mesmo.

Obrigado

Em ter, 18 de jun de 2019 às 15:12, Anderson Oliveira Bezerra <
notifications@github.com> escreveu:
