### ISSUE TITLE
Detalhe de link

### ISSUE THREAD

**Issue by amadorneto** [MicrosoftDocs/xamarin-docs.pt-br#24]
No trecho "Uma versão estendida neste passo a passo pode ser encontrada na repositório GitHub do Mobile CAT que aborda essa parte do exemplo em maior profundidade. " é indicado o link que não existe:
https://github.com/xamarin/mobcat/blob/dev/samples/cppwithxamarin/README.md
O link que funciona é: (com underline em cpp_with_xamarin)
https://github.com/xamarin/mobcat/blob/dev/samples/cpp_with_xamarin/README.md

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Usar bibliotecas de C/C++ com o Xamarin - Xamarin](https://docs.microsoft.com/pt-br/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1660](https://github.com/MicrosoftDocs/xamarin-docs/issues/1660) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @amadorneto

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/xamarin-docs/issues/1660

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
