### ISSUE TITLE
Caminho Errado

### ISSUE THREAD

**Issue by WalissonRodrigo** [MicrosoftDocs/xamarin-docs.pt-br#25]
Estou tentando recuperar o caminho dos dados salvos na memória interna do meu dispositivo Android (Testado) mas quando uso FileSystem.AppDataDirectory ele retorna "/data/data/0/Android/data/meu_pacote_do_projeto/files/..." o que está previamente correto até certo ponto pois o correto seria algo como "/storage/emulated/data/0/Android/data/meu_pacote_do_projeto/files/..."

Como eu poderia retonar a pasta correta do dispositivo usando um código compartilhado?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 91d50947-38a1-44b7-2684-63b17d5bac66
* Version Independent ID: b449b3f5-7a68-fdea-041b-71cc39a46a48
* Content: [Xamarin.Essentials: Auxiliares de sistema de arquivos - Xamarin](https://docs.microsoft.com/pt-br/xamarin/essentials/file-system-helpers?tabs=android#feedback)
* Content Source: [docs/essentials/file-system-helpers.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/essentials/file-system-helpers.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by CeciAc** [comment]
Olá, @WalissonRodrigo 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
