### ISSUE TITLE
Erro ao criar ou importar Assinatura

### ISSUE THREAD

**Issue by fercmparedes** [MicrosoftDocs/xamarin-docs.pt-br#26]
Certificados não estão sendo listados na janela `Assinar e Distribuir` sempre que crio uma nova keystore. Alem disso se tento importar a keystore o Xamarin Visual Studio encerra inesperadamente.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Assinatura do Pacote de Aplicativos Android - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/deploy-test/signing/?tabs=macos#feedback)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Olá, @fercmparedes

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
