### ISSUE TITLE
PlayList

### ISSUE THREAD

**Issue by marcelovargas** [MicrosoftDocs/xamarin-docs.pt-br#27]
How can I use a playlist of videos?

**Comment by lichasu** [comment]
Hello, @marcelovargas ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
