### ISSUE TITLE
Ortografia - PT-BR

### ISSUE THREAD

**Issue by brunofamiliar** [MicrosoftDocs/xamarin-docs.pt-br#28]
"... Ao longo do caminho, SERÃO APRESENTAREMOS FERRAMENTAS, conceitos e etapas necessários para criar e implantar um aplicativo Xamarin.Android."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ba4ac72b-0c09-80b8-7210-c77f1d2a6f42
* Version Independent ID: f39106cc-ec1f-55ea-002a-8928e742b551
* Content: [Olá, Android: Aprofundamento - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/hello-android/hello-android-deepdive?pivots=windows#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/hello-android/hello-android-deepdive.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by srvbpigh** [comment]
Hello, @brunofamiliar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @ brunofamiliar

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/xamarin/android/get-started/hello-android/hello-android-deepdive?pivots=windows#feedback

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
