### ISSUE TITLE
Where is the example on how to customize Material Entry Renderer on iOS

### ISSUE THREAD

**Issue by MathewLC** [MicrosoftDocs/xamarin-docs.pt-br#29]
I am't seeing the example on how to customize iOS material Render and i actually need this. I need to customize the keyboard of my iOS entry but i also need to apply material visual. And when i apply the visual marker to the component, i can't do the changes. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Visual de material do Xamarin. Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/visual/material-visual#feedback)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @MathewLC
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2091](https://github.com/MicrosoftDocs/xamarin-docs/issues/2091) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @MathewLC

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/2091

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
