### ISSUE TITLE
Code isn't running on the latest VS 2019 stable version.

### ISSUE THREAD

**Issue by movisis** [MicrosoftDocs/xamarin-docs.pt-br#30]
In the past, I could detect if designMode was enabled, and make changes to XAML Preview only for design mode.
But for now, the code isn't running at all.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7008caa8-8acd-9d45-9689-f92b48e78bbf
* Version Independent ID: a94b2057-d8c4-eabd-ca9b-b0de07b468b8
* Content: [Visualizar XAML para Xamarin. Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/xaml/xaml-previewer/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by srvbpigh** [comment]
Hello, @movisis
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @movisis 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
