### ISSUE TITLE
Ótima explicação em relação a Páginas Modais do Xamarin.Forms.

### ISSUE THREAD

**Issue by lemarcelo** [MicrosoftDocs/xamarin-docs.pt-br#31]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 4dbd0d0d-484d-ea90-3a8c-e0780a058017
* Version Independent ID: cf200dae-4d45-cc32-e323-c317e969ac64
* Content: [Páginas modais do Xamarin.Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/app-fundamentals/navigation/modal#Popping_Pages_from_the_Modal_Stack)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/modal.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/xamarin-forms/app-fundamentals/navigation/modal.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @lemarcelo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @lemarcelo

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
