### ISSUE TITLE
404 – Página não encontrada

### ISSUE THREAD

**Issue by luizpires** [MicrosoftDocs/xamarin-docs.pt-br#32]
Ao clicar no link de GridLayoutDemo (exemplo) você recebe 404 – Página não encontrada.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6c7acf3a-9bf8-b5a9-1f9d-4bd91296355d
* Version Independent ID: 13c644dd-acda-2457-74d3-a17e82ad90d1
* Content: [GridLayout - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/user-interface/layouts/grid-layout#feedback)
* Content Source: [docs/android/user-interface/layouts/grid-layout.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/android/user-interface/layouts/grid-layout.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by srvbpigh** [comment]
Hello, @luizpires
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2182](https://github.com/MicrosoftDocs/xamarin-docs/issues/2182) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Olá, @luizpires 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/xamarin-docs/issues/2182. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
