### ISSUE TITLE
Hot Reload não funciona

### ISSUE THREAD

**Issue by Nathaniel-Santos** [MicrosoftDocs/xamarin-docs.pt-br#33]
Mesmo seguindo todos os passos informados, ainda continua sem funcionar. Curiosamente no caminho ferramentas &gt; opções &gt; Xamarin ... Não existe a opção Hot reupload pra mim. Ja reinstalei o software mais simplesmente não aparece a opção Hot reupload, nem HotReload nesse caminho. Ja estou a meses sem solução pra esse problema.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [Hot recarregamento de XAML para Xamarin. Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/xaml/hot-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by srvbpigh** [comment]
Hello, @Nathaniel-Santos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2264](https://github.com/MicrosoftDocs/xamarin-docs/issues/2264) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @Nathaniel-Santos 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/xamarin-docs/issues/2264

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by conceptdev** [comment]
[Como relatar um problema com o Visual Studio ou com o Instalador do Visual Studio](https://docs.microsoft.com/pt-br/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
