### ISSUE TITLE
Problema para gerar arquivo morto

### ISSUE THREAD

**Issue by samuelgfm** [MicrosoftDocs/xamarin-docs.pt-br#35]
Fiz todos estes procedimentos e mesmo assim não consigo gerar o arquivo morto para distribuir na App Store. Não sei o que devo fazer para funcionar.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publicar aplicativos Xamarin.iOS na App Store - Xamarin](https://docs.microsoft.com/pt-br/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=macos#feedback)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @samuelgfm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @samuelgfm

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
