### ISSUE TITLE
The link from the images are broken

### ISSUE THREAD

**Issue by vhoyer** [MicrosoftDocs/xamarin-docs.pt-br#5]
O link das imagens está quebrado

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 711d54ad-842b-2141-95b3-fc71d053dbac
* Version Independent ID: be8e8253-7014-1065-ee9b-27a41d35b1ec
* Content: [Temas - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/themes/)
* Content Source: [docs/xamarin-forms/user-interface/themes/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/user-interface/themes/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gosali** [comment]
Hello, @vhorne , 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by gosali** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #379](https://github.com/MicrosoftDocs/xamarin-docs/issues/379) via [**ZenHub**](https://www.zenhub.com/)

**Comment by conceptdev** [comment]
At @DavidPrio's request the 379 issue has been closed. This should be addressed here, it is definitely a localization pipeline problem and not an English source problem.





looks like the space in the `![ ](` image markdown causes an issue in **localized** repos?? i don't know why the space is being introduced - something about multiple images appearing in the same 'line'?

```
![](images/standard-none-sml.png "Controles sem temas") ![ ] (images/standard-light-sml.png "controles com tema claro") ![ ] (images/standard-dark-sml.png "controles com tema escuro")
```

<img width="668" alt="41671791-00780c6e-746d-11e8-999a-5dded049a628" src="https://user-images.githubusercontent.com/199373/41731666-cc5db0a6-7533-11e8-854b-ca404910a50d.png">


> NOTE: there is no space in the English markdown, not sure where that is being introduced in the workflow

```
![](images/standard-none-sml.png "Controls without Theming") ![](images/standard-light-sml.png "Controls with Light Theme") ![](images/standard-dark-sml.png "Controls with Dark Theme")
```

## another example...

```
![](images/boxview-light-sml.png "BoxView com um tema claro StyleClass") ![ ] (images/boxview-dark-sml.png "BoxView com StyleClass um tema escuro")
```



<img width="661" alt="41671793-02cd22b0-746d-11e8-813c-3e621fbf7a07" src="https://user-images.githubusercontent.com/199373/41731665-cc4530da-7533-11e8-9554-9ed3f638379b.png">

**Comment by gosali** [comment]
Hello, @vhoyer , 

  
Thank you for your feedback. 

  
We are actively reviewing your comments and will get back to you soon. 

 
Kind regards, 

Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Olá, @vhoyer , 
 
Agradecemos seus comentários. 

Nossa equipe de engenharia analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/themes/.  

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
