### ISSUE TITLE
Error - foundation.monotouchexception - Xamarin

### ISSUE THREAD

**Issue by crashkill** [MicrosoftDocs/xamarin-docs.pt-br#6]
[Ao clicar no Histórico de Chamadas, ocorrer o erro de foundation.monotouchexception]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: f960f02f-b51e-fa98-a74c-a842518510a2
* Version Independent ID: be0af449-b28c-1042-fe1a-1c9a21d2d170
* Content: [Multitela Hello, iOS - Xamarin](https://docs.microsoft.com/pt-br/xamarin/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive)
* Content Source: [docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by DavidPrio** [comment]
Olá, @crashkill , 
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by gosali** [comment]
Olá, @crashkill  

Agradecemos seus comentários. 

Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @crashkill,  

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
