### ISSUE TITLE
Part of the code is wrong in Phoneword.Droid

### ISSUE THREAD

**Issue by MatheusLealAquino** [MicrosoftDocs/xamarin-docs.pt-br#7]
In the class PhoneDialer, on the line "var intent = new Intent(Intent.ActionCall);" the right code is "var intent = new Intent(Intent.ActionDial);"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Início rápido do Xamarin.Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by MatheusLealAquino** [comment]
Hi @davidbritch

Oh I understood.

But in my device with API 25 doesn't work the ActionCall and when I tried to find a solutition I found the code on the GitHub and there is using the ActionDial and worked so I thinked have something wrong on the tutorial but how you explained to me I think could be something wrong with my device.

Thanks to the answer!

**Comment by davidbritch** [comment]
Yes, you can close this issue.

**Comment by LisandroSu** [comment]
Closing as requested.
