### ISSUE TITLE
Não existe

### ISSUE THREAD

**Issue by BrianSouza** [MicrosoftDocs/xamarin-docs.pt-br#8]
Não encontrei a opção  Gerenciador de SDK do Xamarin na modificação da minha instalação.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Configurando o SDK do Android para o Xamarin.Android - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/installation/android-sdk?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by gosali** [comment]
Olá, @<nome do GITHUB do colaborador>,   
 
Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação.  
 
Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS.   

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal.  

Agradecemos sua contribuição aos nossos artigos.   
CC @nokura 
Atenciosamente,  
Equipe Internacional do Microsoft DOCS

**Comment by mgmclemore** [comment]
Actually, this is a documentation issue -- the latest installer no longer lists "Xamarin SDK Manager" as an option (it lists "Android SDK Setup" instead). I will update the doc accordingly.
